
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WPF_18
{

using System;
    using System.Collections.Generic;
    
public partial class Accounting
{

    public int ID { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string ThirdName { get; set; }

    public Nullable<int> MondayDetailsNumber { get; set; }

    public Nullable<int> ToesdayDetailsNumber { get; set; }

    public Nullable<int> WednesdayDetailsNumber { get; set; }

    public Nullable<int> ThursdayDetailsNumber { get; set; }

    public Nullable<int> FridayDetailsNumber { get; set; }

    public string Workshop { get; set; }

    public string Product { get; set; }

    public Nullable<int> Price { get; set; }

}

}
